# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
warnings_are_errors: true

before_install:
  - sudo apt-get install -y libproj-dev libgeos-dev gdal-bin libgdal-dev libgit2-dev

addons:
  apt:
    packages:
      - libudunits2-dev

after_success:
  - Rscript -e 'devtools::install();devtools::test()'
  - Rscript -e 'library(covr); codecov()'

